platform :ios, '17.6'

target 'Rabbit_iOS' do
  use_frameworks!

  pod 'Alamofire', '~> 5.11'
end

post_install do |installer|
  # CocoaPods [CP] Embed Pods Frameworks 需要 rsync 写入 .app，须关闭 User Script Sandboxing。
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
    end
  end
  installer.aggregate_targets.each do |aggregate_target|
    aggregate_target.user_project.native_targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
      end
    end
    aggregate_target.user_project.build_configurations.each do |config|
      config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
    end
  end
end
